language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install --timeout=30 -q Django==$DJANGO
  - pip install --timeout=30 -q -e .
script:
  - make test
