language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
- DJANGO=1.11
- DJANGO=2.0
- DJANGO=2.2
- DJANGO=3.0
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO=2.0
  - python: '2.7'
    env: DJANGO=2.2
  - python: '2.7'
    env: DJANGO=3.0
  - python: '3.4'
    env: DJANGO=2.2
  - python: '3.4'
    env: DJANGO=3.0
  - python: '3.5'
    env: DJANGO=3.0
install:
- python -m pip install -U pip==18.0
- pipenv install --skip-lock
- pip install --timeout=30 -q Django==$DJANGO
- pip install --timeout=30 -q -e .
script:
- make ci
after_success:
- coveralls
deploy:
  provider: pypi
  user: Ben.Timby
  password:
    secure: vOgW3h6d7qjfSsAl2x7uemohARMPjIQul+fFoyaBqO2iYe3t2z3z1OcuJobqmZw5fpp/c0DXndJmAE3I5UfmhNA9GeB/1nSWAcHXNF5nLqmkqcp4qgO+/zs9zKL1D6Jt+be8SDKXpVGIf3aNlIXgh9d7BjdRNMkkAwKZO0PtoClsDfpHn71nuB3IZRpLq45pXKn29fl8exc2iB38W43Bnu+Vp+bDvKFIBgJFdEvGo6RyK0eJBkUG1CH3K7ZPxdIBdcMWY1zdjp+VcisF9MnPjb2EVnerYo7iHxftVFolbs+3dAm5RbygZ2mA9JWfENIPzFrRzZ1oDwwfPrsWUiPsedmv0H5Rnr30wCNr/gG9sOGkkkr8xpKNTgZHspAkMYw1WwSHVuIwZuiI8XUdzRAJquXMpNVPlKFNjB6+/ehL8gEq3r00uIgQczlfJWG+2o7iQrt022Rg5IS/YKXepBqcCX3xSvy1rXWgQlvnZWII4FsptwCtbnpf1Ckp3kNLbfm7CwLEXeKyZva+XwL94Nb1o2x4fqs1F75WpO7mMUi3A8XUqSD8jwl2muvASq3/qKIVakUcLC6lSzDgzbJDO0KB+jkh7YkZ8bPpubkxbvz3sRXX+90t0JwcFAegyXBND6lyYoDjJQm7xcxhrzD4wlmx0IXvq9rbrPmnxXqw5POMMew=
  on:
    tags: true
  skip_existing: true
