name: CI
on: [push, pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
        django-version: [ '1.11', '2.0', '2.1', '2.2', '3.0', '3.1', '3.2' ]
        pyjwt-version: [ '1.7.1', '2.3.0' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          python -m pip install -U pip~=21.0
          pipenv install --dev --skip-lock
          pip install --timeout=30 -q Django==${{ matrix.django-version }}
          pip install --timeout=30 -q PyJWT==${{ matrix.pyjwt-version }}
          pip install --timeout=30 -q -e .

      - name: Run tests
        run: make ci

      - name: Coveralls
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pipenv run coveralls --service=github
