name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy to PyPI
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: pipenv install --dev --skip-lock

      - name: Build distribution
        run: pipenv run python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
